-- Database setup for onboarding legal documents
-- Run this in your Supabase SQL editor

-- 1. Create the legal_documents table
CREATE TABLE IF NOT EXISTS public.legal_documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  document_type TEXT NOT NULL,
  version TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  is_latest BOOLEAN DEFAULT FALSE,
  published_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 2. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_legal_documents_type_latest ON public.legal_documents(document_type, is_latest);
CREATE INDEX IF NOT EXISTS idx_legal_documents_published ON public.legal_documents(published_at);

-- 3. Insert sample Terms of Service
INSERT INTO public.legal_documents (
  document_type, 
  version, 
  title, 
  content, 
  is_latest, 
  published_at
) VALUES (
  'terms_of_service',
  '1.0',
  'Terms of Service',
  '<h1>Terms of Service</h1>
   <h2>1. Acceptance of Terms</h2>
   <p>By accessing and using Quillaborn, you accept and agree to be bound by the terms and provision of this agreement.</p>
   
   <h2>2. Use License</h2>
   <p>Permission is granted to temporarily download one copy of the materials (information or software) on Quillaborn for personal, non-commercial transitory viewing only.</p>
   
   <h2>3. Disclaimer</h2>
   <p>The materials on Quillaborn are provided on an ''as is'' basis. Quillaborn makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
   
   <h2>4. Limitations</h2>
   <p>In no event shall Quillaborn or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Quillaborn, even if Quillaborn or a Quillaborn authorized representative has been notified orally or in writing of the possibility of such damage.</p>
   
   <h2>5. Revisions and Errata</h2>
   <p>The materials appearing on Quillaborn could include technical, typographical, or photographic errors. Quillaborn does not warrant that any of the materials on its website are accurate, complete or current.</p>
   
   <h2>6. Links</h2>
   <p>Quillaborn has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Quillaborn of the site.</p>
   
   <h2>7. Site Terms of Use Modifications</h2>
   <p>Quillaborn may revise these terms of use for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these Terms and Conditions of Use.</p>',
  true,
  NOW()
);

-- 4. Insert sample Privacy Policy
INSERT INTO public.legal_documents (
  document_type, 
  version, 
  title, 
  content, 
  is_latest, 
  published_at
) VALUES (
  'privacy_policy',
  '1.0',
  'Privacy Policy',
  '<h1>Privacy Policy</h1>
   <p>Your privacy is important to us. It is Quillaborn''s policy to respect your privacy regarding any information we may collect while operating our website.</p>
   
   <h2>1. Information We Collect</h2>
   <p>We collect information you provide directly to us, such as when you create an account, complete your profile, or communicate with us. This may include:</p>
   <ul>
     <li>Name and contact information</li>
     <li>Profile information (bio, pronouns, interests)</li>
     <li>Account credentials</li>
     <li>Communication preferences</li>
   </ul>
   
   <h2>2. How We Use Your Information</h2>
   <p>We use the information we collect to:</p>
   <ul>
     <li>Provide, maintain, and improve our services</li>
     <li>Process transactions and send related information</li>
     <li>Send you technical notices, updates, and support messages</li>
     <li>Respond to your comments and questions</li>
     <li>Communicate with you about products, services, and events</li>
   </ul>
   
   <h2>3. Information Sharing</h2>
   <p>We do not share, sell, or otherwise disclose your personal information for purposes other than those outlined in this Privacy Policy. However, we may disclose your personal information to a third party for a business purpose.</p>
   
   <h2>4. Data Security</h2>
   <p>We have implemented measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure.</p>
   
   <h2>5. Data Retention</h2>
   <p>We will retain your personal information only for as long as necessary to fulfill the purposes outlined in this Privacy Policy.</p>
   
   <h2>6. Your Rights</h2>
   <p>You have the right to:</p>
   <ul>
     <li>Access your personal information</li>
     <li>Correct inaccurate personal information</li>
     <li>Request deletion of your personal information</li>
     <li>Object to processing of your personal information</li>
   </ul>
   
   <h2>7. Changes to This Privacy Policy</h2>
   <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
   
   <h2>8. Contact Us</h2>
   <p>If you have any questions about this Privacy Policy, please contact us.</p>',
  true,
  NOW()
);

-- 5. Set up RLS (Row Level Security) policies
ALTER TABLE public.legal_documents ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read legal documents
CREATE POLICY "Allow authenticated users to read legal documents" ON public.legal_documents
  FOR SELECT USING (auth.role() = 'authenticated');

-- Allow service role to manage legal documents
CREATE POLICY "Allow service role to manage legal documents" ON public.legal_documents
  FOR ALL USING (auth.role() = 'service_role'); 