-- RPC function to complete onboarding
-- This function handles all database updates when a user completes onboarding
CREATE OR REPLACE FUNCTION public.complete_onboarding(
  user_id UUID,
  bio_text TEXT DEFAULT NULL,
  pronoun_id INTEGER DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result JSON;
BEGIN
  -- Update the user's profile with bio, pronouns, and mark onboarding as complete
  UPDATE public.profiles 
  SET 
    bio = bio_text,
    pronoun_id = pronoun_id,
    onboarding_complete = true,
    updated_at = NOW()
  WHERE id = user_id;
  
  -- Return success response
  SELECT json_build_object(
    'success', true,
    'message', 'Onboarding completed successfully',
    'user_id', user_id
  ) INTO result;
  
  RETURN result;
  
EXCEPTION
  WHEN OTHERS THEN
    -- Return error response
    SELECT json_build_object(
      'success', false,
      'error', SQLERRM,
      'user_id', user_id
    ) INTO result;
    
    RETURN result;
END;
$$;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION public.complete_onboarding(UUID, TEXT, INTEGER) TO authenticated; 

-- Waitlist approval token table (for invite tracking)
CREATE TABLE IF NOT EXISTS public.waitlist_approval_tokens (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  used_at TIMESTAMPTZ NULL,
  used_by UUID NULL
);

CREATE INDEX IF NOT EXISTS idx_waitlist_tokens_email ON public.waitlist_approval_tokens(email);
CREATE INDEX IF NOT EXISTS idx_waitlist_tokens_used ON public.waitlist_approval_tokens(used_at);

ALTER TABLE public.waitlist_approval_tokens ENABLE ROW LEVEL SECURITY;
-- Allow inserting/verifying by authenticated admins via policies you define.
-- For basic read during verification in a route, use server-side supabase client (RLS applies to end users).

-- Waitlist table enhancements
-- Optional name column for personalization
ALTER TABLE public.waitlist
  ADD COLUMN IF NOT EXISTS name TEXT;

-- Case-insensitive uniqueness support (if not already present)
ALTER TABLE public.waitlist
  ADD COLUMN IF NOT EXISTS email_norm TEXT GENERATED ALWAYS AS (lower(btrim(email))) STORED;

DO $$ BEGIN
  CREATE UNIQUE INDEX IF NOT EXISTS waitlist_email_norm_key ON public.waitlist(email_norm);
EXCEPTION WHEN others THEN NULL; END $$;
